#!/bin/bash

# Copyright (c) 2011-2012, Cyril Adrian <cyril.adrian@gmail.com> All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
#  - Redistributions of source code must retain the above copyright notice, this list of conditions and the
#    following disclaimer.
#
#  - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#    following - disclaimer in the documentation and/or other materials provided - with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

pack=${PROJECT_PACK:-$(dirname $(dirname $(readlink -f $0)))}
test -d "$pack" || exit 1

. $pack/bash_profile.sh

test -d "$PROJECTS_DIR" || exit 1

CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/dmenu_project
(
    if test "`ls -dt $PROJECTS_DIR "$CACHE" 2> /dev/null | sed 1q`" != "$CACHE"; then
        mkdir -p "`dirname "$CACHE"`" && ls $PROJECTS_DIR | sort -u > "$CACHE"
    fi
)
if project=$(dmenu -b -i -p 'Project:' -fn fixed -nb '#3f3f3f' -nf ivory -sb '#285577' -sf white < "$CACHE"); then
    PROFILE=$PROJECTS_DIR/$project/.dmenu_profile
    test -e $PROFILE || cat > $PROFILE <<EOF
set -p

export PROJECT_PACK=$pack

if [ -e \$HOME/.bash_profile ]; then
    . \$HOME/.bash_profile
elif [ -e $HOME/.bashrc ]; then
    . \$HOME/.bashrc
fi
. \$PROJECT_PACK/bash_profile.sh

go_to_project $project
echo "DISPLAY=$DISPLAY emacs -g 132x50" | at now 2>/dev/null

EOF

    if [ -x $(which gnome-terminal) ]; then
        exec gnome-terminal --geometry=132x50 --title="Project: $project" --hide-menubar --command="bash --init-file $PROFILE"
    fi
    exec xterm +bc +cm -cr white -cu -en 'utf-8' -fa Inconsolata -fs 9 -j -ms white -rightbar -rw -s -sb -si -sk -sl 4294967296 -sm -u8 -vb -wc +wf -w 4 -bd '#3f3f3f' -bg '#3f3f3f' -fg ivory -geometry 132x50 -title "Project: $project" -n "Project: $project" -e bash --init-file $PROFILE
fi
