#!/bin/bash

# Copyright (c) 2010-2013, Cyril Adrian <cyril.adrian@gmail.com> All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
#
#  - Redistributions of source code must retain the above copyright notice, this list of conditions and the
#    following disclaimer.
#
#  - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#    following - disclaimer in the documentation and/or other materials provided - with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

pack=${PROJECT_PACK:-$(dirname $(dirname $(readlink -f $0)))}
test -d "$pack" || exit 1

. $pack/bash_profile.sh

test -d "$PROJECTS_DIR" || exit 1

CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/zenity_project
(
    if test "`ls -dt $PROJECTS_DIR "$CACHE" 2> /dev/null | sed 1q`" != "$CACHE"; then
        mkdir -p "`dirname "$CACHE"`" && ls $PROJECTS_DIR | sort -u > "$CACHE"
    fi
)

ask() {
    if [[ -x $(which yad 2>/dev/null) ]]; then
        yad --width 300 --height 400 --list --title="Open a project" --column="Project" --search-column=1 --regex-search --no-headers --separator="" < "$CACHE"
    elif [[ -x $(which zenity 2>/dev/null) ]]; then
        zenity --width 300 --height 400 --list --title="Open a project" --column="Project" --separator="" < "$CACHE"
    else
        echo "No yad nor zenity found" >&2
        exit 1
    fi
}

if project=$(ask); then
    if [ x"$project" != x ]; then
        PROFILE=$PROJECTS_DIR/$project/.zenity_profile
        cat > $PROFILE <<EOF
set -p
export PROJECT_PACK=$pack

if [ -e \$HOME/.bash_profile ]; then
    . \$HOME/.bash_profile
elif [ -e $HOME/.bashrc ]; then
    . \$HOME/.bashrc
fi
. \$PROJECT_PACK/bash_profile.sh

_ssh_agent_check
go_to_project $project

#at now 2>/dev/null <<eof
#DISPLAY=$DISPLAY; export DISPLAY
emacs -g 132x50 &
disown -a -h
#eof
EOF

        if [[ -x $(which gnome-terminal 2>/dev/null) ]]; then
            exec gnome-terminal --geometry=132x50 --title="Project: $project" --hide-menubar --command="bash --init-file $PROFILE"
        elif [[ -x $(which xterm 2>/dev/null) ]]; then
            exec xterm +bc +cm -cr white -cu -en 'utf-8' -fa Inconsolata -fs 10 -j -ms white -rightbar +tb -rw -s -sb -si -sk -sl 4294967296 -sm -u8 -vb -wc +wf -w 4 -bd '#3f3f3f' -bg '#3f3f3f' -fg ivory -geometry 132x50 -title "Project: $project" -n "Project: $project" -e bash --init-file $PROFILE
        else
            echo "No gnome-terminal nor xterm found" >&2
            exit 1
        fi
    fi
else
    exit 1
fi
