#!/bin/bash

pack=${PROJECT_PACK:-$(dirname $(dirname $(readlink -f $0)))}
test -d "$pack" || exit 1

. $pack/bash_profile.sh

test -d "$PROJECTS_DIR" || exit 1

CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/zenity_project
(
    if test "`ls -dt $PROJECTS_DIR "$CACHE" 2> /dev/null | sed 1q`" != "$CACHE"; then
        mkdir -p "`dirname "$CACHE"`" && ls $PROJECTS_DIR | sort -u > "$CACHE"
    fi
)

if project=$(zenity --list --title "Open a project" --column "Project" < "$CACHE"); then
    if [ x"$project" != x ]; then
        PROFILE=$PROJECTS_DIR/$project/.zenity_profile
        test -e $PROFILE || cat > $PROFILE <<EOF
set -p
export PROJECT_PACK=$pack

if [ -e \$HOME/.bash_profile ]; then
    . \$HOME/.bash_profile
elif [ -e $HOME/.bashrc ]; then
    . \$HOME/.bashrc
fi
. \$PROJECT_PACK/bash_profile.sh

go_to_project $project
echo "DISPLAY=$DISPLAY emacs -g 132x50" | at now 2>/dev/null
EOF

        if [ -x $(which gnome-terminal) ]; then
            exec gnome-terminal --geometry=132x50 --title="Project: $project" --hide-menubar --command="bash --init-file $PROFILE"
        fi
        exec xterm +bc +cm -cr white -cu -en 'utf-8' -fa Inconsolata -fs 9 -j -ms white -rightbar -rw -s -sb -si -sk -sl 4294967296 -sm -u8 -vb -wc +wf -w 4 -bd '#3f3f3f' -bg '#3f3f3f' -fg ivory -geometry 132x50 -title "Project: $project" -n "Project: $project" -e bash --init-file $PROFILE
    fi
fi
